#!/opt/homebrew/bin/node

let fs = require("fs");
let Phrase = require("robdom-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  fs.writeFile('palindromes.txt', line, err => {
    if (err) {
      console.log(err)
      return
    }
  });
});
