#!/opt/homebrew/bin/node

let fs = require("fs");
let Phrase = require("robdom-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    fs.writeFileSync('palindromes.txt', line + "\n", {flag: 'a+'}, function (err) {
      if (err) return console.log(err);
    });
    console.log("This line was written to palindromes.txt: ", line)
    // console.log("palindrome detected:", line);
  }
});
